export const APP_ROUTES = {
    AUTH: '/auth/login',
    ADMIN: {
        DASHBOARD: '/admin/dashboard',
        PROGRAMMES: '/admin/programmes',
        CANDIDATURES: '/admin/candidatures',
        USERS: '/admin/users',
        HISTORIQUE: '/admin/historique',
        EVALUATIONS: '/admin/evaluations',
        REPORTING: '/admin/reporting',
        MATCHING: '/admin/matching',
        CALENDRIER: '/admin/calendrier',
        PARAMETRES: '/admin/parametres',
    },
    COACH: {
        DASHBOARD: '/coach/dashboard',
        PROGRAMMES: '/coach/programmes',
        ENTREPRENEURS: '/coach/entrepreneurs',
        SESSIONS: '/coach/sessions',
        LIVRABLES: '/coach/deliverables',
        CALENDRIER: '/coach/calendar',
        REPORT: '/coach/report',
        CHAT: '/coach/chat',
    },
    ENTREPRENEUR: {
        DASHBOARD: '/entrepreneur/dashboard',
        BOOK: '/entrepreneur/book',
        SESSIONS: '/entrepreneur/sessions',
        TASKS: '/entrepreneur/tasks',
        DELIVERABLES: '/entrepreneur/deliverables',
        COACH: '/entrepreneur/coach',
        CHAT: '/entrepreneur/chat',
        STATUS: '/entrepreneur/status',
    },
} as const;
